name: minivtop
description: Mini VTOP is an unofficial VIT Bhopal University VTOP website app that uses the power of WebView to create a user-friendly app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.11.1+11

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # For material you.
  dynamic_color: ^1.7.0

  # For WebView.
  flutter_inappwebview: ^6.0.0

  # For state management.
  flutter_riverpod: ^2.5.1

  # For material animations on list and grid.
  animations: ^2.0.11

  # For circular progress gauges. Ex: CGPA indicator.
  syncfusion_flutter_gauges: ^25.1.35

  # For calendar views in app.
  clean_calendar: ^1.1.0

  # For custom animations.
  rive: ^0.13.1

  # For shimmer/loading effect.
  shimmer: ^3.0.0

  # For parsing HTML doc from WebView.
  html: ^0.15.4

  # For cropping captcha image.
  image: ^4.1.7

  # For loading animations.
  flutter_spinkit: ^5.2.0

  # For firebase packages. After installing new firebase package run ```flutterfire configure```.
  firebase_core: ^2.27.1

  # For logging errors.
  firebase_crashlytics: ^3.4.19

  # For logging usage and behavior data.
  firebase_analytics: ^10.8.10

  # For fetching VTOP controlling data.
  cloud_firestore: ^4.15.9

  # For identifying logs user.
  uuid: ^4.3.3

  # For storing user preferences, app themeMode, app version, VTOP loaded HTML docs and firebase controller vars.
  shared_preferences: ^2.2.2

  # For getting app package information.
  package_info_plus: ^4.2.0

  # For storing userID and password.
  flutter_secure_storage: ^9.0.0

  # For providing path for device directory to hive.
  path_provider: ^2.1.2

  # For splash screen.
  flutter_native_splash: ^2.4.0

  # For launching links in app ex: privacy policy and terms and conditions.
  url_launcher: ^6.2.5

  # For color picking.
  flex_color_picker: ^3.4.1

  # For working easily with collections like list.
  collection: ^1.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/rive/
    - assets/splash_icon/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Black.ttf
        - asset: fonts/LexendDeca-Bold.ttf
        - asset: fonts/LexendDeca-ExtraBold.ttf
        - asset: fonts/LexendDeca-ExtraLight.ttf
        - asset: fonts/LexendDeca-Light.ttf
        - asset: fonts/LexendDeca-Medium.ttf
        - asset: fonts/LexendDeca-Regular.ttf
        - asset: fonts/LexendDeca-SemiBold.ttf
        - asset: fonts/LexendDeca-Thin.ttf
        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
